#!/bin/sh

rsync="/usr/bin/rsync -avHz --delete"
mirror=mirrors.rit.edu::centos

verlist="6 7"
archlist="x86_64"
baselist="os updates addons extras isos centosplus storage cloud virt xen xen4 SCL"
local=/var/www/html/centos

for ver in $verlist
do
  for arch in $archlist
  do
    for base in $baselist
    do
        remote=$mirror/$ver/$base/$arch/
        $rsync $remote $local/$ver/$base/$arch/
    done
  done
done
